<a href="https://colab.research.google.com/github/ousseeema/data-science/blob/main/01_SF_Salaries_Exercise_correction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'> <img src='../../Pierian_Data_Logo.png' /></a>
___

# SF Salaries Exercise

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [1]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal.**

In [5]:
df = pd.read_csv("sal.csv")

** Check the head of the DataFrame. **

In [6]:
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

** Use the .info() method to find out how many entries there are.**

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [8]:
df["BasePay"].mean()

66325.4488404877

** What is the highest amount of OvertimePay in the dataset ? **

In [9]:
df["OvertimePay"].max()

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [12]:
df.loc[df["EmployeeName"]=="JOSEPH DRISCOLL",["EmployeeName","JobTitle"] ]

       EmployeeName                   JobTitle
24  JOSEPH DRISCOLL  CAPTAIN, FIRE SUPPRESSION

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [15]:
df.loc[df["EmployeeName"]=="JOSEPH DRISCOLL", ["EmployeeName", "TotalPayBenefits"]]

       EmployeeName  TotalPayBenefits
24  JOSEPH DRISCOLL         270324.91

** What is the name of highest paid person (including benefits)?**

In [18]:
df.loc[df["TotalPayBenefits"].max() ==df["TotalPayBenefits"] , ["EmployeeName", "TotalPayBenefits"]]

     EmployeeName  TotalPayBenefits
0  NATHANIEL FORD         567595.43

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [20]:
df.loc[df['TotalPayBenefits']== df["TotalPayBenefits"].min(), ]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [30]:
df.groupby("Year").agg({"BasePay":"mean"})

           BasePay                 TotalPay
               sum        max           sum
Year
2011  2.299566e+09  294580.02  2.594195e+09
2012  2.405835e+09  302578.00  2.724848e+09
2013  2.576381e+09  319275.01  2.918656e+09
2014  2.537369e+09  318835.49  2.876911e+09

** How many unique job titles are there? **

In [34]:
df["JobTitle"].nunique()

2159

** What are the top 5 most common jobs? **

In [35]:
df["JobTitle"].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

[texte du lien](https://)** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [42]:
num_unique_job_titles_2013 = sum(df[df['Year'] == 2013]['JobTitle'].value_counts() == 1)
num_unique_job_titles_2013

202

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [52]:
def checkTitle(title):
  if("Chief" in title):
    return 1
  else:
    return 0

In [54]:
df["JobTitle"].apply(checkTitle).sum()

423

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

In [51]:
df["JobTitleLength"] = df["JobTitle"].apply(len)
df[["JobTitleLength", "TotalPayBenefits"]].corr()

                  JobTitleLength  TotalPayBenefits
JobTitleLength          1.000000         -0.036878
TotalPayBenefits       -0.036878          1.000000

# Great Job!