<a href="https://colab.research.google.com/github/ousseeema/data-science/blob/main/projet_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#imporation de pandas , numpy, matplotlib,seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# read the files
data = pd.read_excel("imap_export.xls")
#project the dataframe
data

,Data Export - Filters applied: (none) Data As Of Aug 2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Factory Name,Factory Type,Product Type Type,"Nike, Inc. Brand(s)",Events,Supplier Group,Address,City,State,Postal Code,Country / Region,Region,Total Workers,Line Workers,% Female Workers,% Migrant Workers
1,EVEREST TEXTILE CO LTD,MATERIALS,Apparel,Nike,NaN,EVEREST TEXTILE,No 256 Minghe Village,Tainan City,Tainan,743002,Taiwan,N ASIA,1439,811,51,57
2,Big Game Sports,FINISHED GOODS,Equipment,Nike,Collegiate,BIG GAME SPORTS,13835 Welch Rd,Dallas,Texas,75244,USA,AMERICAS,68,51,36,0
3,PT Semarang Garment,FINISHED GOODS,Apparel,Nike,NaN,KUKDONG,JL Soekarno Hatta Km 25,Semarang,Jawa Tengah,50552,Indonesia,S ASIA,3851,3462,94,0
4,Charmgo (Cambodia) Co. Ltd,FINISHED GOODS,Apparel,Nike,NaN,CHARMGO,Pham Bostanei Kuhn Kaheing Srok Samrongtong Ka...,Kampong Spey,Kampong Spueu,05207,Cambodia,SE ASIA,1557,1526,71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,PT Victory Chingluh Indonesia,FINISHED GOODS,Footwear,Nike,NaN,CHING LUH,JL Raya Pasarkemis Rajeg,Tangerang,Banten,15560,Indonesia,S ASIA,4014,3475,55,0
633,"Olive Apparel (Cambodia) Co., Ltd.",FINISHED GOODS,Apparel,Nike,NaN,RAMATEX,National Road No 3 Phum Prey Kambot,Phnom Penh,Phnom Penh,120910,Cambodia,SE ASIA,1274,1107,89,0
634,PT. Kanindo Makmur Jaya,FINISHED GOODS,Equipment,Nike,Collegiate,KANAAN,Jalan Raya Jepara Kudus,Jepara,Jawa Tengah,59462,Indonesia,S ASIA,6680,6582,62,0
635,South Island Garment Sdn Bhd,FINISHED GOODS,Apparel,Nike,Collegiate,SOUTH ISLAND,2468 Solok Perusahaan Dua,Perai,Pulau Pinang,13600,Malaysia,S ASIA,621,344,53,82
636,"Toyama Sports Goods Co., Ltd.",FINISHED GOODS,Equipment,Nike,NaN,TOYAMA SPORTS,345 Fukumitsu,Nanto,Toyama,939-1637,Japan,N ASIA,3,2,0,0

In [ ]:
# We noticed that the column names are in the first row, so we reset the format by assigning the first row as column names.
# Then, we removed the first row (which contained the column names) from the data and reset the index.
data.columns=["Factory Name","Factory Type","Product Type","Brand","Events","Supplier Group","Address","City","State","Postal Code","Country","Region","Total Workers","Line Workers","Female Workers","Migrant Workers"]
data = data.iloc[1:]
data= data.reset_index(drop=True)
data.head()

,Factory Name,Factory Type,Product Type,Brand,Events,Supplier Group,Address,City,State,Postal Code,Country,Region,Total Workers,Line Workers,Female Workers,Migrant Workers
0,EVEREST TEXTILE CO LTD,MATERIALS,Apparel,Nike,NaN,EVEREST TEXTILE,No 256 Minghe Village,Tainan City,Tainan,743002,Taiwan,N ASIA,1439,811,51,57
1,Big Game Sports,FINISHED GOODS,Equipment,Nike,Collegiate,BIG GAME SPORTS,13835 Welch Rd,Dallas,Texas,75244,USA,AMERICAS,68,51,36,0
2,PT Semarang Garment,FINISHED GOODS,Apparel,Nike,NaN,KUKDONG,JL Soekarno Hatta Km 25,Semarang,Jawa Tengah,50552,Indonesia,S ASIA,3851,3462,94,0
3,Charmgo (Cambodia) Co. Ltd,FINISHED GOODS,Apparel,Nike,NaN,CHARMGO,Pham Bostanei Kuhn Kaheing Srok Samrongtong Ka...,Kampong Spey,Kampong Spueu,05207,Cambodia,SE ASIA,1557,1526,71,1
4,SAN FANG (TR1) (CHINA),MATERIALS,Footwear,Nike,NaN,SAN FANG,YUE YUEN INDUSTRIAL PARK,"DONGGUAN, GUANGDONG",Guangdong,511700,China,N ASIA,307,225,20,0

In [ ]:
#info of data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Factory Name     636 non-null    object
 1   Factory Type     636 non-null    object
 2   Product Type     636 non-null    object
 3   Brand            636 non-null    object
 4   Events           148 non-null    object
 5   Supplier Group   636 non-null    object
 6   Address          636 non-null    object
 7   City             635 non-null    object
 8   State            636 non-null    object
 9   Postal Code      636 non-null    object
 10  Country          636 non-null    object
 11  Region           636 non-null    object
 12  Total Workers    636 non-null    object
 13  Line Workers     636 non-null    object
 14  Female Workers   636 non-null    object
 15  Migrant Workers  636 non-null    object
dtypes: object(16)
memory usage: 79.6+ KB

In [ ]:
#Delete unnecessary columns,Replace NaN values with a specific value
data.fillna({'Events':"Collegiate"}, inplace= True)
data.drop(["Address","Postal Code"], axis=1, inplace= True)
data.head()

,Factory Name,Factory Type,Product Type,Brand,Events,Supplier Group,City,State,Country,Region,Total Workers,Line Workers,Female Workers,Migrant Workers
0,EVEREST TEXTILE CO LTD,MATERIALS,Apparel,Nike,Collegiate,EVEREST TEXTILE,Tainan City,Tainan,Taiwan,N ASIA,1439,811,51,57
1,Big Game Sports,FINISHED GOODS,Equipment,Nike,Collegiate,BIG GAME SPORTS,Dallas,Texas,USA,AMERICAS,68,51,36,0
2,PT Semarang Garment,FINISHED GOODS,Apparel,Nike,Collegiate,KUKDONG,Semarang,Jawa Tengah,Indonesia,S ASIA,3851,3462,94,0
3,Charmgo (Cambodia) Co. Ltd,FINISHED GOODS,Apparel,Nike,Collegiate,CHARMGO,Kampong Spey,Kampong Spueu,Cambodia,SE ASIA,1557,1526,71,1
4,SAN FANG (TR1) (CHINA),MATERIALS,Footwear,Nike,Collegiate,SAN FANG,"DONGGUAN, GUANGDONG",Guangdong,China,N ASIA,307,225,20,0

In [ ]:
# Adding a column that contains the number of male workers and the total number of workers excluding immigrants.
data["Male Workers"]= data["Total Workers"] - data["Female Workers"]
data["Total Workers excluding immigrants"]= data["Total Workers"] - data["Migrant Workers"]
data.head()

,Factory Name,Factory Type,Product Type,Brand,Events,Supplier Group,City,State,Country,Region,Total Workers,Line Workers,Female Workers,Migrant Workers,Male Workers,Total Workers excluding immigrants
0,EVEREST TEXTILE CO LTD,MATERIALS,Apparel,Nike,Collegiate,EVEREST TEXTILE,Tainan City,Tainan,Taiwan,N ASIA,1439,811,51,57,1388,1382
1,Big Game Sports,FINISHED GOODS,Equipment,Nike,Collegiate,BIG GAME SPORTS,Dallas,Texas,USA,AMERICAS,68,51,36,0,32,68
2,PT Semarang Garment,FINISHED GOODS,Apparel,Nike,Collegiate,KUKDONG,Semarang,Jawa Tengah,Indonesia,S ASIA,3851,3462,94,0,3757,3851
3,Charmgo (Cambodia) Co. Ltd,FINISHED GOODS,Apparel,Nike,Collegiate,CHARMGO,Kampong Spey,Kampong Spueu,Cambodia,SE ASIA,1557,1526,71,1,1486,1556
4,SAN FANG (TR1) (CHINA),MATERIALS,Footwear,Nike,Collegiate,SAN FANG,"DONGGUAN, GUANGDONG",Guangdong,China,N ASIA,307,225,20,0,287,307